### ISSUE TITLE
새로운 DB 계정 업데이트 내역 반영해줄 사람을 구합니다

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#35]
자세한 설명은 여기에 있는 부분들을 적용해주시고..
https://discord.com/channels/1186220164438564864/1187239605515333652/1187239609596395520

변경사항이 있는 부분 중 git 이 트래킹하는 변경 사항에 대해 수정된 PR 을 올려주세요

**Comment by Higangssh** [comment]
제가 작업완료했습니다
