### ISSUE TITLE
myPage.jsp 레이아웃 수정 

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#39]
페이지 폭이 작아질때 문제가 발생합니다

![image](https://github.com/cloudchamb3r/Animalls/assets/98369677/7e0379b5-5fd0-40fb-916a-abca7999492e)

**Comment by SSONGTJ** [comment]
제가 할게요.

**Comment by cloudchamb3r** [comment]
#39 에서 확인했습니다
