### ISSUE TITLE
브랜드 페이지 작성

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#43]
![image](https://github.com/cloudchamb3r/Animalls/assets/98369677/076b4106-9e71-4a05-9adf-2bca6ed1d085)
브랜드 페이지를 눌렀을때 나오게 할 간단한 페이지 작성해주실 분을 구합니다

@delve1 @SSONGTJ @ddaahhmm @Higangssh @ugamezeRepo @ran2rrrw

**Comment by SSONGTJ** [comment]
제가 할게요.

**Comment by cloudchamb3r** [comment]
#51 에서 확인 완료했습니다
