### ISSUE TITLE
ReviewDto 필드의 네이밍을 수정해주세요

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#61]
![Screenshot_2023-12-21-19-55-35-184_com.github.android.jpg](https://github.com/cloudchamb3r/Animalls/assets/98369677/1dc7bda7-f9fd-4b50-9bd2-ec90990abe3e)
 
연관된 dao역시 camelCase로 수정해주세요

**Comment by Higangssh** [comment]
제가 하겟습니다

**Comment by cloudchamb3r** [comment]
#66 에서 해결 완료
