### ISSUE TITLE
FileDto 필드의 네이밍을 수정해주세요

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#62]
![Screenshot_2023-12-21-19-59-54-897_com.github.android.jpg](https://github.com/cloudchamb3r/Animalls/assets/98369677/f5d8a9ce-ea96-40e6-8412-a2bcd0bc4ab5)

연관된 dao역시 camelCase로 수정해주세요

**Comment by Higangssh** [comment]
네 알겟습니다

**Comment by cloudchamb3r** [comment]
#66 에서 해결 완료
