### ISSUE TITLE
이메일 인증 기능 구현

### ISSUE THREAD

**Issue by cloudchamb3r** [cloudchamb3r/Animalls#81]
회원 가입시에 인증용으로 사용할 이메일 인증 기능을 구현합니다

- [x] 이메일 전송 기능 구현
- [x] 이메일 인증 기능 구현

**Comment by cloudchamb3r** [comment]
제가 이메일 인증 구현하겠습니다

**Comment by cloudchamb3r** [comment]
#83 에서 전송 기능 구현 완료하였습니다

**Comment by ugamezeRepo** [comment]
제가 이메일 인증 기능 구현하겠습니다.
